---
name: password_manager
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  flutter_string_encryption: ^0.3.1
  provider: ^4.3.1
  modal_progress_hud: ^0.1.3
  http: ^0.12.2
  cupertino_icons: ^0.1.2
  page_transition: ^1.1.6
  flutter_spinkit: ^4.1.2+1
  cached_network_image: ^2.3.1
  animated_button: ^0.1.2
  shimmer: ^1.1.1
  lottie: ^0.6.0
  image_picker: ^0.6.7+7
  firebase_storage: ^3.1.6
  fluttertoast: ^7.0.4
  auto_size_text: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
